# Generated by Django 5.1.7 on 2025-05-24 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPostSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('scheduled_time', models.DateTimeField()),
                ('posted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_bot_token', models.CharField(blank=True, max_length=200)),
                ('discord_channel_id', models.CharField(blank=True, max_length=100)),
                ('reddit_client_id', models.CharField(blank=True, max_length=100)),
                ('reddit_client_secret', models.CharField(blank=True, max_length=100)),
                ('reddit_user_agent', models.CharField(blank=True, max_length=200)),
                ('reddit_subreddit', models.CharField(blank=True, default='all', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
