# Generated by Django 5.1.7 on 2025-05-24 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_discordmessageschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordmessageschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
